import Head from "next/head";
import { ReactElement, useEffect, useState } from "react";
import { correctPassword } from "../../lib/auth";
import MainAd from "../../components/ad";
import {
  findAd,
  getContentWithID,
  pingContentData,
  registerView,
} from "../../lib/requests/frontend";
import { createContentData, getContentIDS } from "../../lib/requests/backend";
import { loadEnvConfig } from "@next/env";
import CornerLogo from "../../components/logo";
import ReactiveCountdown from "../../components/countdown";
import ReactiveAdInfo from "../../components/ad/info";
import NotSeriousFooter from "../../components/footer";

function AdPage(props: any): ReactElement {
  const ad = props.ad;
  const content = props.content;
  const [isDone, setIsDone] = useState(false);

  useEffect(() => {
    console.log("Registering view");
    if (ad.id && content.id) registerView(ad.id, content.id);
  }, [ad.id, content.id]);

  if (!ad || !content) return <div>Ad not found</div>;
  // TODO Warning: Cannot update a component (`AdPage`) while rendering a different component (`Countdown$1`). To locate the bad setState() call inside `Countdown$1`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render

  return (
    <div className="py-0 px-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen  flex-1 flex flex-col">
        <CornerLogo />
        <div className="flex items-center flex-wrap flex-col relative pt-48 lg:relative lg:pt-24 md:pt-48 mx-10">
          <div className="overflow-auto m-4 ml-0 mr-0 mt-0 p-0 pt-0 flex flex-col text-inherit border-2 border-solid border-gray-300 border-opacity-60 rounded-xl transition-colors duration-200 ease hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:border-blue-600 active:text-blue-600">
            <MainAd ad={ad} content={content} setIsDone={setIsDone} />

            <div className="flex flex-row p-4 pt-2 pb-3 text-left justify-between">
              <ReactiveAdInfo ad={ad} />

              <ReactiveCountdown
                ad={ad}
                content={content}
                isDone={isDone}
                setIsDone={setIsDone}
              />
            </div>
          </div>
        </div>
      </main>
      <NotSeriousFooter />
    </div>
  );
}
export default AdPage;

export async function getStaticProps({ params }: any) {
  const { id } = params;
  let content;
  let ad;

  try {
    content = await getContentWithID(id);

    let tags = content.tags.map((tag: { tag: any }) => tag.tag);
    let theme = content.theme;

    ad = await findAd(tags, theme);
  } catch (error) {
    return { notFound: true };
  }

  return {
    props: {
      ad,
      content,
    },
    revalidate: 7200, // one hour
  };
}

export async function getStaticPaths() {
  loadEnvConfig("../../.env.local");
  var ids: { id: string }[];

  if (!correctPassword) throw new Error("Password is not set in .env.local");
  ids = await getContentIDS(correctPassword);

  const paths = ids.map((id: { id: string }) => {
    return {
      params: {
        id: id.id,
      },
    };
  });

  for (const id in ids) {
    await pingContentData(ids[id].id).catch(async (e) => {
      console.log(
        "Contentdata not found for id: " + ids[id].id,
        ". Creating... (",
        e,
        ")"
      );
      await createContentData(ids[id].id, correctPassword);
    });
  }

  return {
    paths,
    fallback: "blocking",
  };
}
