import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Countdown from "react-countdown";

// dont use this, just inspo. Use tailwind. Tho this works as insporation. Image needs to be bigger.

const Home: NextPage = () => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-8 px-0 flex-1 flex flex-col ">
        <div className="items-end justify-start flex">
          <Image
            src="/mads.svg"
            alt="Vercel Logo"
            width={300 * 0.3}
            height={128 * 0.3}
          />
        </div>
        <div className="flex items-center justify-center flex-wrap">
          <a className="m-4 mt-0 p-0 pt-0 flex flex-col text-inherit border-2 border-solid border-gray-300 border-opacity-60 rounded-xl transition-colors duration-200 ease hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600 active:border-blue-600 active:text-blue-600">
            <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              <Image
                src={"/ad.png"}
                alt="Deploy"
                height={630 * 1.2}
                width={1200 * 1.2}
                layout="intrinsic"
              />
            </a>
            <div className="flex flex-row p-4 pt-2 pb-3 text-left justify-between">
              <p className="justify-start">
                Currently viewing Actual Guns 3D by PixelPoly digital.
              </p>
              <Countdown
                date={Date.now() + 5000}
                precision={1}
                intervalDelay={1000}
                className=""
                renderer={(props) => {
                  if (props.seconds > 0) {
                    return (
                      <a
                        className="text-xl font-bold"
                        onClick={() => {
                          console.log("Hi");
                        }}
                      >
                        {props.seconds}
                      </a>
                    );
                  }

                  return <a href="https://google.com" className="text-xl font-bold ">Skip</a>
                }}
              />
            </div>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-8 px-0 border-t-2 border-solid border-gray-300 justify-center items-center">
        <a
          href="https://vercel.com"
          target="_blank"
          rel="noopener noreferrer"
          className="flex "
        >
          Made with ❤️ and Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
